Repository CaribesTIC/vue-tdd, pull requests merged in 2023-04, with the labels that each got.

#44 feat: Migrate to vitepress version
  docs/.vitepress/cache/deps/@theme_index.js
  docs/.vitepress/cache/deps/@theme_index.js.map
  docs/.vitepress/cache/deps/_metadata.json
  docs/.vitepress/cache/deps/vue.js
  docs/.vitepress/cache/deps/vue.js.map
  docs/.vitepress/config.ts
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/style.css
  docs/index.md
  docs/vitest/entorno-de-prueba.md
  docs/vth/probando-eventos-emitidos.md
  docs/vth/probando-propiedades.md
  docs/vth/propiedades-calculadas.md
  docs/vth/simulando-la-entrada-del-usuario.md
  docs/vth/simulando-objetos-globales.md
  docs/vth/talonando-componentes.md
  docs/vtu/esencial/entorno-de-prueba.md
  docs/vtu/esencial/un-curso-acelerado.md
  docs/vtu/vue-test-utils-en-profundidad/probando-vuex.md
  package-lock.json
  package.json
Labels: enhancement

#45 style: Put sh file type
  docs/.vitepress/cache/deps/_metadata.json
  docs/vth/vuex-mutaciones.md
Labels: enhancement

#46 fix: Link paths
  docs/.vitepress/config.ts
  docs/index.md
Labels: documentation

#48 fix: Automocking algorithm
  docs/vitest/simulaciones.md
Labels: bug, documentation
